---
- include_vars: Debian.yml
  when: ansible_os_family == "Debian"

- name: Updating package list
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Adding jessie-backports repo
  apt_repository:
    repo: deb http://httpredir.debian.org/debian jessie-backports main contrib non-free
    update_cache: yes

- name: installing the required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ required_packages }}"

- name: Forcing zoneminder to be installed from jessie-backports
  apt:
    name: zoneminder
    default_release: jessie-backports

- name: installing required pip packages
  pip:
    name: "{{ required_pip_packages }}"

- name: Creating MySQL database
  mysql_db:
    name: zm
    target: /usr/share/zoneminder/db/zm_create.sql
    state: import
    login_user: root

- name: Creating MySQL user
  mysql_user:
    login_user: root
    name: "{{ zoneminder_mysql_user }}"
    password: "{{ zoneminder_mysql_password }}"
    priv: zm.*:ALL

- name: configuring zm.conf
  template:
    src: zm.conf.j2
    dest: /etc/zm/zm.conf

- name: Configuring permissions on zm.conf
  file:
    path: /etc/zm/zm.conf
    state: file
    group: www-data

- stat:
    path: /etc/zm/apache.conf
  register: stat_apache_conf

- name: Configuring apache2 configuration for zoneminder
  shell: mv /etc/zm/apache.conf /etc/apache2/conf-available/zoneminder.conf
  when: stat_apache_conf.stat.exists



- name: Configuring to start zoneminder on boot
  systemd:
    name: zoneminder
    enabled: yes

- name: Configuring PHP timezone
  lineinfile:
    path: /etc/php5/apache2/php.ini
    regexp: "^;date.timezone = "
    line: "date.timezone = {{ ansible_date_time.tz }}"

    
- name: Enabling required apache2 modules
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - "{{ apache2_modules }}"

- name: Enabling required apache2 configuration
  shell: a2enconf zoneminder
  notify: "{{ item }}"
  with_items:
    - "reload apache2"
    - "start zoneminder"
