---
- include_vars: Debian.yml
  when: ansible_os_family == "Debian"

- include_vars: main.yml

- name: Updating package list
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Adding jessie-backports repo
  apt_repository:
    repo: deb http://httpredir.debian.org/debian jessie-backports main contrib non-free
    update_cache: yes

- name: Importing dotdeb GPG key into apt-keyring
  apt_key:
    url: https://dotdeb.org/dotdeb.gpg
    state: present

- name: Adding dotdeb repo (for PHP7)
  apt_repository:
    repo: "{{ item }}"
    update_cache: yes
  with_items:
    - "{{ dotdeb_repo }}"

- name: installing the required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ required_packages }}"

- name: installing required pip packages
  pip:
    name: "{{ required_pip_packages }}"


- name: Installing zoneminder
  apt:
    name: zoneminder
    state: present

- name: Creating MySQL database
  mysql_db:
    name: zm
    target: /usr/share/zoneminder/db/zm_create.sql
    state: import
    login_user: root

- name: Creating MySQL user
  mysql_user:
    login_user: root
    name: "{{ zoneminder_mysql_user }}"
    password: "{{ zoneminder_mysql_password }}"
    priv: zm.*:ALL

- name: Configuring permissions on zm.conf
  file:
    path: /etc/zm/zm.conf
    state: file
    group: www-data

- name: Configuring to start zoneminder on boot
  systemd:
    name: zoneminder
    enabled: yes

- name: Enabling required apache2 modules
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - "{{ apache2_modules }}"

- name: Enabling required apache2 configuration
  shell: a2enconf zoneminder
  notify: "{{ item }}"
  with_items:
    - "reload apache2"
    - "start zoneminder"
