---
- include_vars: Debian.yml
  when: ansbile_os_family == "Debian"

- name: Updating package list
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Installing the required packages
  apt:
    name: item
    state: present
  with_items:
    - "{{ required_apt_packages }}"

- name: Adding jessie-backports repo
  apt_repository:
    repo: deb http://httpredir.debian.org/debian jessie-backports main contrib non-free
    update_cache: yes

- name: Installing zoneminder
  apt:
    name: zoneminder
    state: present
